#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xmldiff
Version  : 2.4
Release  : 3
URL      : https://files.pythonhosted.org/packages/76/36/a3e41bf7c01f1110d7b5589ca74d2927d3736a5b43ee63053faf3483b991/xmldiff-2.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/76/36/a3e41bf7c01f1110d7b5589ca74d2927d3736a5b43ee63053faf3483b991/xmldiff-2.4.tar.gz
Summary  : Creates diffs of XML files
Group    : Development/Tools
License  : MIT
Requires: xmldiff-bin = %{version}-%{release}
Requires: xmldiff-python = %{version}-%{release}
Requires: xmldiff-python3 = %{version}-%{release}
Requires: lxml
Requires: setuptools
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : lxml
BuildRequires : setuptools
BuildRequires : six

%description
========

%package bin
Summary: bin components for the xmldiff package.
Group: Binaries

%description bin
bin components for the xmldiff package.


%package python
Summary: python components for the xmldiff package.
Group: Default
Requires: xmldiff-python3 = %{version}-%{release}

%description python
python components for the xmldiff package.


%package python3
Summary: python3 components for the xmldiff package.
Group: Default
Requires: python3-core
Provides: pypi(xmldiff)
Requires: pypi(lxml)
Requires: pypi(setuptools)
Requires: pypi(six)

%description python3
python3 components for the xmldiff package.


%prep
%setup -q -n xmldiff-2.4
cd %{_builddir}/xmldiff-2.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1632249151
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xmldiff
/usr/bin/xmlpatch

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
